### ISSUE TITLE
Need to be able to set MQTT Client ID

### ISSUE THREAD

**Issue by kidmock** [pletch/tiltbridge_mqtt#1]
The MQTT client is defaulting to "tiltbridge" so if you have multiple clients publishing to the same topic. Last client to connect wins

Perhaps, you can use the same name as the mdns name?

**Comment by pletch** [comment]
I can either have the topic default to tiltbridge or I can add the option to specify the topic in the settings page.  Any thoughts on which would be preferable?

**Comment by kidmock** [comment]
It's NOT the topic that's the problem. It's the client ID, the client ID needs to be unique. As you see here the client is always using client ID tiltbridge. 

1608402484: New client connected from 10.250.40.160 as mosq-DrnvbDLQnNV5999MU5 (p2, c1, k60, u'mosquitto').
1608405779: Client tiltbridge already connected, closing old connection.
1608405779: New client connected from 10.250.40.187 as tiltbridge (p2, c1, k30000).
1608405794: New connection from 10.250.40.183 on port 1883.
1608405794: Client tiltbridge already connected, closing old connection.
1608405794: New client connected from 10.250.40.183 as tiltbridge (p2, c1, k30000).

**Comment by pletch** [comment]
Ah yes, I understand now.  I'll have it pick up the mDNS name as you initially suggested.

**Comment by pletch** [comment]
The mqtt client name is now consistent with the mDNS name for the tiltbridge.  I also forgot I already had topic as a configurable parameter (it has been a while since i looked at this...).  Looking at my mosquitto logs, it appears to work as intended though I only have a single tiltbridge device at the moment to test with.

**Comment by kidmock** [comment]
Perfect, thanks. If you're ever in the Detroit/Ann Arbor Area I own you a beer!
