### ISSUE TITLE
MQTT Authentication is failing. 

### ISSUE THREAD

**Issue by kidmock** [pletch/tiltbridge_mqtt#2]
When I try to connect to my MQTT broker with username and password:

I get

1608399080: New connection from tiltbridge on port 1883.
1608399080: Socket error on client <unknown>, disconnecting.

However, If I remove the username and password options and connect anonymously I can connect and publish just fine.

**Comment by pletch** [comment]
I will admit I didnt' test using authentication as thoroughly as I probably should I have.  I will try to determine why this is failing and get a fix in.

**Comment by pletch** [comment]
This should be addressed with the latest commit.  I enabled authentication on my local mqtt server and it appeared to work for me.  Let me know if you still have trouble.

**Comment by kidmock** [comment]
This is fixed as well
